name: bench
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: phi-ag/setup-binaryen@v1

      - name: Install wasm-tools
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-tools

      - name: Install MoonBit
        # if: ${{ matrix.os.name != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s -- bleeding
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Run benchmark
        run: |
          deno task prebench
          deno task bench | tee bench-output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: "benchmarkjs"
          output-file-path: bench-output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: bench-pages
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          # fail-on-alert: true
